title: GreenMonty
description: A website with a blog
footer_text: Copyright 2021 Bruno Pawroznik
header_feature_image: ../uploads/pawel-czerwinski-7fpy4bvvqwo-unsplash.jpg
header_text: I am the Glob-glo-gab-galab, The shwabble-dabble-wabble-gabble
  flibba blabba blab
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/ryan-phillips-pidjfnvoxy0-unsplash.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
