title: GreenMonty
description: A website with a blog
footer_text: Harry Banks 2021 ©
header_feature_image: ../uploads/19-tame-impala-the-slow-rush-neil-krug.jpg
header_text: Fonts Within Music
header_text_color: "#c5a072"
bannerheight: 50vmax
navbarheight: 55px
logo: ../uploads/greenmonty-logo-again.png
favicon: ../uploads/ryan-phillips-pidjfnvoxy0-unsplash.ico
gridlayout: false
fixednavbar: false
upzoom: true
items:
  - name: About the Author
    siteurl: file:///Users/19059522/Downloads/aboutme/index.htm\
