title: GreenMonty
description: A website with a blog
footer_text: Copyright 2021 Bruno Pawroznik
header_feature_image: ../uploads/pawel-czerwinski-7fpy4bvvqwo-unsplash.jpg
header_text: Fonts Throughout Music History
header_text_color: "#c5a072"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/ryan-phillips-pidjfnvoxy0-unsplash.png
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
