title: GreenMonty
description: A website with a blog
footer_text: Harry Banks 2021 ©
header_feature_image: ../uploads/19-tame-impala-the-slow-rush-neil-krug.jpg
header_text: Fonts Throughout Music History
header_text_color: "#c5a072"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/green-monty-logo.jpg
favicon: ../uploads/ryan-phillips-pidjfnvoxy0-unsplash.ico
gridlayout: false
fixednavbar: false
upzoom: true
